steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'training/Dockerfile'
      - '-t'
      - 'YOUR_DOCKER_REGISTRY/trainer:latest'
      - '.'
images:
  - 'YOUR_DOCKER_REGISTRY/trainer:latest'
